### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by nongdenchet** [nongdenchet/coder_snap#1]
Here is the assignment 2 /cc @coderschoolreview

**Comment by nvh0412** [comment]
Hi @nongdenchet , nice work with such a beautiful submission and clean code :+1:

The goals of this homework are:
- to know how to implement authentication from scratch in Rails with the help of the `has_secure_password` class method and the `brypt` gem (while understanding what they do under the hood)
- to design a more complex schema for a web app and be more familiar with ActiveRecord API such as custom foreign keys for `belongs_to`/`has_many`, using `has_many :through` and building more advanced queries by chaining `where`, `order`, and `merge`
- to build more complex forms in views that involve multiple models.

## Quick review:
- Use `has_secure_password` in User
- Use `bcrypt` and `rails_12factor` gems in Gemfile
- Define `current_user` correctly
- Correctly handle user signup in Users controller and user login in Sessions controller
- Use validations for important columns
- Use `message` partial
- Correctly define `belongs_to`/`has_many` with custom class_name and foreign_id
- Correctly use `has_many :through` for friendship
- You have followed basic [Ruby style guide](https://github.com/styleguide/ruby)

## Detailed review

Gemfile:
- Correct grouping of test/development gems
  Routes file:
- Good RESTful routes with `resources` method
- Clean custom routes
  Controllers:
- Nice, you had defined `current_user` in `ApplicationController` and use `helper_method` to make it available for the view

Views:
- Your views are carefully implemented, you implemented partial views and good use of built-in rails helpders

Congrats again on the submission. Let us know if you have any feedback.

**Comment by nongdenchet** [comment]
Thank alot for your review <3 <3 <3
